### ISSUE TITLE
unable to find user mobsf: no matching entries in passwd file

### ISSUE THREAD

**Issue by theblockstalk** [fundacaocerti/mobsf-action#20]
Receiving this error when try to run with .apk file

> [Build App locally and run security analysis/security-test2] failed to start container: Error response from daemon: unable to find user mobsf: no matching entries in passwd file

```yaml
security-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run MobSF Analysis
        uses: fundacaocerti/mobsf-action@v1.7.2
        env:
          INPUT_FILE_NAME: ./TonomyID.apk
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report
```
